# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MAIN_WINDOW.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(786, 683)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(214, 207, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 178, 102))
        gradient.setColorAt(0.55, QtGui.QColor(235, 148, 61))
        gradient.setColorAt(0.98, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 178, 102))
        gradient.setColorAt(0.55, QtGui.QColor(235, 148, 61))
        gradient.setColorAt(0.98, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 178, 102))
        gradient.setColorAt(0.55, QtGui.QColor(235, 148, 61))
        gradient.setColorAt(0.98, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 207, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 178, 102))
        gradient.setColorAt(0.55, QtGui.QColor(235, 148, 61))
        gradient.setColorAt(0.98, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 178, 102))
        gradient.setColorAt(0.55, QtGui.QColor(235, 148, 61))
        gradient.setColorAt(0.98, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 178, 102))
        gradient.setColorAt(0.55, QtGui.QColor(235, 148, 61))
        gradient.setColorAt(0.98, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 178, 102))
        gradient.setColorAt(0.55, QtGui.QColor(235, 148, 61))
        gradient.setColorAt(0.98, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 178, 102))
        gradient.setColorAt(0.55, QtGui.QColor(235, 148, 61))
        gradient.setColorAt(0.98, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 178, 102))
        gradient.setColorAt(0.55, QtGui.QColor(235, 148, 61))
        gradient.setColorAt(0.98, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0))")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.x1_dim = QtWidgets.QSpinBox(self.groupBox_2)
        self.x1_dim.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.x1_dim.setProperty("value", 2)
        self.x1_dim.setObjectName("x1_dim")
        self.gridLayout_3.addWidget(self.x1_dim, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.y_dim = QtWidgets.QSpinBox(self.groupBox_2)
        self.y_dim.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.y_dim.setProperty("value", 3)
        self.y_dim.setObjectName("y_dim")
        self.gridLayout_3.addWidget(self.y_dim, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.x2_dim = QtWidgets.QSpinBox(self.groupBox_2)
        self.x2_dim.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.x2_dim.setProperty("value", 1)
        self.x2_dim.setObjectName("x2_dim")
        self.gridLayout_3.addWidget(self.x2_dim, 1, 1, 1, 1)
        self.x3_dim = QtWidgets.QSpinBox(self.groupBox_2)
        self.x3_dim.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.x3_dim.setProperty("value", 2)
        self.x3_dim.setObjectName("x3_dim")
        self.gridLayout_3.addWidget(self.x3_dim, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_3.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radio_combined_cheb = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_combined_cheb.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.radio_combined_cheb.setChecked(True)
        self.radio_combined_cheb.setObjectName("radio_combined_cheb")
        self.verticalLayout.addWidget(self.radio_combined_cheb)
        self.radio_laguerre = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_laguerre.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.radio_laguerre.setObjectName("radio_laguerre")
        self.verticalLayout.addWidget(self.radio_laguerre)
        self.custom_check = QtWidgets.QCheckBox(self.groupBox_3)
        self.custom_check.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.custom_check.setObjectName("custom_check")
        self.verticalLayout.addWidget(self.custom_check)
        self.ownStructure = QtWidgets.QComboBox(self.groupBox_3)
        self.ownStructure.setObjectName("ownStructure")
        self.ownStructure.addItem("")
        self.ownStructure.addItem("")
        self.ownStructure.addItem("")
        self.ownStructure.addItem("")
        self.ownStructure.addItem("")
        self.verticalLayout.addWidget(self.ownStructure)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.x3_deg = QtWidgets.QSpinBox(self.groupBox_4)
        self.x3_deg.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.x3_deg.setProperty("value", 2)
        self.x3_deg.setObjectName("x3_deg")
        self.gridLayout_4.addWidget(self.x3_deg, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.x2_deg = QtWidgets.QSpinBox(self.groupBox_4)
        self.x2_deg.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.x2_deg.setProperty("value", 1)
        self.x2_deg.setObjectName("x2_deg")
        self.gridLayout_4.addWidget(self.x2_deg, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.x1_deg = QtWidgets.QSpinBox(self.groupBox_4)
        self.x1_deg.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.x1_deg.setSingleStep(1)
        self.x1_deg.setProperty("value", 2)
        self.x1_deg.setObjectName("x1_deg")
        self.gridLayout_4.addWidget(self.x1_deg, 0, 1, 1, 1)
        self.bruteforce_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.bruteforce_btn.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.bruteforce_btn.setObjectName("bruteforce_btn")
        self.gridLayout_4.addWidget(self.bruteforce_btn, 3, 0, 1, 2)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 2)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_8.setObjectName("groupBox_8")
        self.radioConjucateGrad = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioConjucateGrad.setGeometry(QtCore.QRect(20, 20, 231, 20))
        self.radioConjucateGrad.setObjectName("radioConjucateGrad")
        self.radioLSTM = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioLSTM.setGeometry(QtCore.QRect(20, 50, 231, 20))
        self.radioLSTM.setObjectName("radioLSTM")
        self.horizontalLayout.addWidget(self.groupBox_8)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)
        self.line_input = QtWidgets.QLineEdit(self.groupBox)
        self.line_input.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.line_input.setObjectName("line_input")
        self.gridLayout_5.addWidget(self.line_input, 2, 0, 1, 1)
        self.select_input = QtWidgets.QToolButton(self.groupBox)
        self.select_input.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.select_input.setObjectName("select_input")
        self.gridLayout_5.addWidget(self.select_input, 2, 1, 1, 1)
        self.line_output = QtWidgets.QLineEdit(self.groupBox)
        self.line_output.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.line_output.setObjectName("line_output")
        self.gridLayout_5.addWidget(self.line_output, 3, 0, 1, 1)
        self.select_output = QtWidgets.QToolButton(self.groupBox)
        self.select_output.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.select_output.setObjectName("select_output")
        self.gridLayout_5.addWidget(self.select_output, 3, 1, 1, 1)
        self.sample_spin = QtWidgets.QSpinBox(self.groupBox)
        self.sample_spin.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.sample_spin.setMaximum(999)
        self.sample_spin.setProperty("value", 36)
        self.sample_spin.setObjectName("sample_spin")
        self.gridLayout_5.addWidget(self.sample_spin, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.weights_box = QtWidgets.QComboBox(self.groupBox_7)
        self.weights_box.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.weights_box.setObjectName("weights_box")
        self.weights_box.addItem("")
        self.weights_box.addItem("")
        self.weights_box.addItem("")
        self.horizontalLayout_2.addWidget(self.weights_box)
        self.lambda_check = QtWidgets.QCheckBox(self.groupBox_7)
        self.lambda_check.setStyleSheet("background-color: rgba(255, 178, 102, 255)")
        self.lambda_check.setObjectName("lambda_check")
        self.horizontalLayout_2.addWidget(self.lambda_check)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout.setObjectName("gridLayout")
        self.predictBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.predictBox.setVisible(False)
        self.predictBox.setObjectName("predictBox")
        self.gridLayout.addWidget(self.predictBox, 3, 2, 1, 1)
        self.plot_button = QtWidgets.QPushButton(self.groupBox_6)
        self.plot_button.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.plot_button.setObjectName("plot_button")
        self.gridLayout.addWidget(self.plot_button, 1, 2, 2, 2)
        self.exec_button = QtWidgets.QPushButton(self.groupBox_6)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 184, 184))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.exec_button.setPalette(palette)
        self.exec_button.setAutoFillBackground(False)
        self.exec_button.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.exec_button.setDefault(True)
        self.exec_button.setFlat(False)
        self.exec_button.setObjectName("exec_button")
        self.gridLayout.addWidget(self.exec_button, 1, 0, 2, 2)
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setEnabled(True)
        self.label_10.setVisible(False)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_10.raise_()
        self.predictBox.raise_()
        self.plot_button.raise_()
        self.exec_button.raise_()
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.results_field = QtWidgets.QTextBrowser(Form)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.results_field.setPalette(palette)
        self.results_field.setAutoFillBackground(False)
        self.results_field.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.results_field.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.results_field.setReadOnly(True)
        self.results_field.setObjectName("results_field")
        self.verticalLayout_2.addWidget(self.results_field)

        self.retranslateUi(Form)
        self.weights_box.setCurrentIndex(0)
        self.exec_button.clicked.connect(Form.exec_clicked)
        self.plot_button.clicked.connect(Form.plot_clicked)
        self.sample_spin.valueChanged['int'].connect(Form.samples_modified)
        self.select_input.clicked.connect(Form.input_clicked)
        self.select_output.clicked.connect(Form.output_clicked)
        self.x1_dim.valueChanged['int'].connect(Form.dimension_modified)
        self.x2_dim.valueChanged['int'].connect(Form.dimension_modified)
        self.x3_dim.valueChanged['int'].connect(Form.dimension_modified)
        self.x1_deg.valueChanged['int'].connect(Form.degree_modified)
        self.x2_deg.valueChanged['int'].connect(Form.degree_modified)
        self.x3_deg.valueChanged['int'].connect(Form.degree_modified)
        self.radio_combined_cheb.toggled['bool'].connect(Form.type_modified)
        self.radio_laguerre.toggled['bool'].connect(Form.type_modified)
        Form.output_changed['QString'].connect(self.line_output.setText)
        Form.input_changed['QString'].connect(self.line_input.setText)
        self.line_input.textChanged['QString'].connect(Form.input_modified)
        self.line_output.textChanged['QString'].connect(Form.output_modified)
        self.lambda_check.toggled['bool'].connect(Form.lambda_calc_method_changed)
        self.weights_box.currentIndexChanged['QString'].connect(Form.weights_modified)
        self.y_dim.valueChanged['int'].connect(Form.dimension_modified)
        self.bruteforce_btn.clicked.connect(Form.bruteforce_called)
        self.custom_check.toggled['bool'].connect(Form.structure_changed)
        self.radioConjucateGrad.toggled['bool'].connect(Form.method_modified)
        self.radioLSTM.toggled['bool'].connect(Form.method_modified)
        self.ownStructure.currentIndexChanged['QString'].connect(Form.ownStructure_modified)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.radio_combined_cheb, self.x1_deg)
        Form.setTabOrder(self.x1_deg, self.x2_deg)
        Form.setTabOrder(self.x2_deg, self.x3_deg)
        Form.setTabOrder(self.x3_deg, self.x1_dim)
        Form.setTabOrder(self.x1_dim, self.x2_dim)
        Form.setTabOrder(self.x2_dim, self.x3_dim)
        Form.setTabOrder(self.x3_dim, self.y_dim)
        Form.setTabOrder(self.y_dim, self.sample_spin)
        Form.setTabOrder(self.sample_spin, self.line_input)
        Form.setTabOrder(self.line_input, self.select_input)
        Form.setTabOrder(self.select_input, self.line_output)
        Form.setTabOrder(self.line_output, self.select_output)
        Form.setTabOrder(self.select_output, self.exec_button)
        Form.setTabOrder(self.exec_button, self.plot_button)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form1"))
        self.groupBox_5.setTitle(_translate("Form", "ВИБІР ПОЛІНОМІВ"))
        self.groupBox_2.setTitle(_translate("Form", "Розмірність"))
        self.label_4.setText(_translate("Form", "X3"))
        self.label_2.setText(_translate("Form", "X1"))
        self.label_3.setText(_translate("Form", "X2"))
        self.label_5.setText(_translate("Form", "Y"))
        self.groupBox_3.setTitle(_translate("Form", "Типи"))
        self.radio_combined_cheb.setText(_translate("Form", "Вид 1"))
        self.radio_laguerre.setText(_translate("Form", "Вид 2"))
        self.custom_check.setText(_translate("Form", "Власна структура"))
        self.ownStructure.setItemText(0, _translate("Form", "sin"))
        self.ownStructure.setItemText(1, _translate("Form", "cos"))
        self.ownStructure.setItemText(2, _translate("Form", "arctan"))
        self.ownStructure.setItemText(3, _translate("Form", "tanh"))
        self.ownStructure.setItemText(4, _translate("Form", "sigmoid"))
        self.groupBox_4.setTitle(_translate("Form", "Степені"))
        self.label_6.setText(_translate("Form", "X1"))
        self.label_7.setText(_translate("Form", "X3"))
        self.label_8.setText(_translate("Form", "X2"))
        self.bruteforce_btn.setText(_translate("Form", "Підібрати"))
        self.groupBox_8.setTitle(_translate("Form", "Метод"))
        self.radioConjucateGrad.setText(_translate("Form", "Метод покоординатного спуску"))
        self.radioLSTM.setText(_translate("Form", "Метод найменших квадратів"))
        self.groupBox.setTitle(_translate("Form", "ДАНI"))
        self.label.setText(_translate("Form", "Вибірка:"))
        self.line_input.setText(_translate("Form", "input.txt"))
        self.line_input.setPlaceholderText(_translate("Form", "Вхідний файл"))
        self.select_input.setText(_translate("Form", "..."))
        self.line_output.setText(_translate("Form", "output.txt"))
        self.line_output.setPlaceholderText(_translate("Form", "Вихідний файл"))
        self.select_output.setText(_translate("Form", "..."))
        self.label_9.setText(_translate("Form", "Ваги:"))
        self.weights_box.setItemText(0, _translate("Form", "Average"))
        self.weights_box.setItemText(1, _translate("Form", "Scaled"))
        self.weights_box.setItemText(2, _translate("Form", "Width_interval"))
        self.lambda_check.setText(_translate("Form", "3-блочні вирази"))
        self.groupBox_6.setTitle(_translate("Form", "ВИКОНАННЯ ПРОГРАМИ"))
        self.plot_button.setText(_translate("Form", "Будувати графіки"))
        self.exec_button.setText(_translate("Form", "Виконати"))
        self.label_10.setText(_translate("Form", "Кроки передбачення:"))
        self.results_field.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Menio Regular\'; font-size:10pt;\"><br /></p></body></html>"))
        self.results_field.setPlaceholderText(_translate("Form", "Результати"))
